//UTA program dictionary class for Na'vi
package udict;

import java.io.*;
import udict.uDict;

public class uDNVlang extends uDict{
 public   static String[] edict = {
"'Rrta /prop.n./", "Earth",
"'a'aw /adj./", "A few, several",
"'ampi /v./", "Touch",
"'ampirikx /n./", "Leaf pitcher plant",
"'ango /adj./", "Soft (of a sound)",
"'angtsìk /n./", "Hammerhead",
"'aw /num./", "One",
"'awkx /n./", "Cliff",
"'awlie /adv./", "Once (in the past)",
"'awlo /adv./", "Once",
"'awm /n./", "Camp",
"'awpo /pn./", "One individual",
"'awsiteng /adv./", "Together",
"'awstengyem /vtr./", "Join two things together (ii)",
"'awve /adj./", "First (ordinal)",
"'awve adj.", "first",
"'e'al /adj./", "Worst",
"'e'al adj.", "worst",
"'efu /vtr./", "Feel, sense, perceive",
"'eko /v./", "Attack",
"'eko n.", "attack",
"'ekong /n./", "Beat (rhythmic)",
"'ekong n.", "beat (rhythmic)",
"'ele'wll /n./", "Thorny paw, cactus",
"'em /vtr./", "Cook",
"'emyu /n./", "Cook, cooker",
"'engeng /adj./", "Level",
"'engeng n.", "level",
"'eoio /adj./", "Ceremonious",
"'evan /n./", "Boy (colloquial)",
"'eve /n./", "Girl (colloquial)",
"'eveng /n./", "Child",
"'eveng n.", "child ",
"'evengan /n./", "Boy",
"'evenge /n./", "Girl",
"'evi /n./", "Kid (affectionate form of)",
"'evi n.", "kid (affectionate form of ''child'')",
"'ewan /adj./", "Young",
"'ewll /n./", "Plant",
"'eylan /n./", "Friend",
"'eyng /v./", "Answer, respond",
"'eyt /n./", "The symbol 8 (not the value eight)",
"'i'a /vin./", "End, conclude",
"'ia /vin./", "Lose oneself (spiritual sense)",
"'it /n./", "Bit, a small amount",
"'it n.", "bit a small amount",
"'itan /n./", "Son",
"'itan n.", "son",
"'ite /n./", "Daughter",
"'ite n.", "daughter",
"'itetsyìp /n./", "Little daughter (term of endearment)",
"'o' /adj./", "Bringing fun, exciting",
"'ok /n./", "Remembrance",
"'ok n.", "remembrance",
"'okrol /n./", "History (ancient)",
"'okvur /n./", "History (nonancient)",
"'om /adj./", "Violet, purple, magenta",
"'ompin /n./", "Violet, purple, magenta",
"'ong /v./", "Unfold, blossom",
"'ong v.", "unfold, blossom ",
"'ongokx /vin./", "Be born",
"'opin /n./", "Color, colour",
"'ora /n./", "Lake",
"'u /n./", "Thing (object, fact, abstraction)",
"'uo /pn./", "Something",
"'upe /inter./", "What (thing)",
"'upe n.", "what (thing)",
"'upxare /n./", "Message",
"'upxare n.", "message",
"'Ìnglìsì /n./", "English language",
"'ä'o /n./", "Pitcher plant",
"'änsyem /adj./", "Complete",
"'ärìp /vtr./", "Move",
"'ì'awn /vin./", "Remain, stay",
"'ì'awn v.", "remain, stay",
"'ìheyu /n./", "Spiral",
"'ìheyu n.", "spiral",
"'ìn /vin./", "Be busy, be occupied",
"'ìnglìsì n.", "English language",
"Amhul n.", "child's name",
"Europa /prop.n./", "Europe",
"Eyaye n.", "Plant species (Warbonnet)",
"Eywa n.", "World spirit guiding force and deity (equivalent to Gaia); Eywa PN",
"Eywa ngahu (expression)", "good-bye, Eywa (be with you) ",
"Iknimaya n.", "Thundering rocks, Stairway to Heaven (floating mountains) ",
"Kelutrel n.", "Hometree Hometree (tree for living in)",
"Lenay'ga n.", "Slinger (predatory creature)",
"Na'vi /prop.n./", "The People, indigenous Pandoran sentient race",
"Na'vi n.", "the People the People (name for themselves)",
"Nìayoeg adj, i", "like us",
"Omatikaya n.", "Blue Flute Clan",
"Pari /prop.n./", "Paris",
"Ralu n.", "child's name",
"Sweriye /prop.n./", "Sweden",
"Tawtute /prop.n./", "Skyperson, human",
"Tawtute n.", "Sky Person ",
"Tsahaylu n.", "bond (neural connection)",
"Tsahìk n.", "matriarch ",
"Uniltaron n.", "Dream Hunt ",
"Utral Aymokriyä n.", "Tree of Voices ",
"Vitrautral /prop.n./", "Tree of Souls",
"Yerik n.", "hexapede, hexapod",
"Yu.E.Sey /prop.n./", "USA",
"a /affix/", "Adjectival attribution and subordination marker",
"a /sbd./", "Which, that",
"a adj.", "which, that ",
"alaksi /adj./", "Ready",
"alaksì adj.", "ready ",
"alo /n./", "Time, turn, instance, one of a number of repeated or",
"alu /conj./", "That is, in other words",
"alunta /conj./", "Because, from the reason",
"alìm /adv./", "Far away, at a distance",
"alìm adj.", "far far away, at a distance",
"anìheyu /n./", "Fibonacci, blue spiral plant",
"apxa /adj./", "Large",
"apxa adj.", "large ",
"apxangrr /n./", "Delta tree",
"asim /adv./", "Nearby, at close range",
"atan /n./", "Light",
"atan adj, n", "light ",
"atanvi /n./", "Ray",
"atokirina' /n./", "Seeds of the great tree",
"atokirina' n.", "Seeds of the great tree",
"atxkxe /n./", "Land",
"atxkxe n.", "land",
"atxkxerel /n./", "Map",
"au /intj./", "Exclamation of consternation",
"au /n./", "Drum (made of skin)",
"au n.", "drum (made of skin)",
"aungia /n./", "Sign, omen",
"aungia n.", "sign, omen",
"awaiei /n./", "Banshee of paradise",
"awnga /pn./", "We",
"ayfo or [ˈaj.fo] /pn./", "They",
"ayfo pn", "they ",
"aylaru /pn./", "To the others",
"aylaru conj.", "to the others (contraction of aylaberu)",
"aynga /pn./", "You all, you (pl.)",
"aynga pn", "you ",
"ayoe /pn./", "We, us (exclusive)",
"ayoe pn", "we (exclusive)",
"ayoeng /pn./", "We, us (inclusive)",
"ayoeng pn", "we (inclusive)",
"ayu /n./", "Things",
"eampin /n./", "Blue, green",
"ean /adj./", "Blue, green",
"ean adj.", "blue ",
"eanean /n./", "Cheadle, herbaceous plant",
"ekxan /n./", "Barricade, obstruction",
"eltu /n./", "Brain",
"eltu lefngap /n./", "Computer",
"eltu n.", "brain ",
"eltu si /vin./", "Pay attention, quit goofing off",
"eltu si v, c", "listen pay attention, quit goofing off",
"eltungawng /n./", "Brainworm",
"eltungawng n.", "brainworm ",
"eltur tìtxen si /vin./", "Be interesting, intriguing",
"emza'u /v./", "Pass (a test), overcome",
"emza'u v.", "pass (a test)",
"eo /adp./", "Before, in front of (place)",
"eo pr", "before, in front of ",
"etrìp /adj./", "Favourable, favorable, auspicious",
"eyawr /adj./", "Correct, right",
"eyaye /n./", "Warbonnet",
"eyk /v./", "Lead",
"eyk v.", "lead ",
"eyktan /n./", "Leader",
"eyktan n.", "leader",
"fa /adp./", "With, by means of",
"fa pr", "with with (by means of)",
"faheu v.", "smell",
"fahew /n./", "Smell",
"faketuan n.", "Alien (i.e. non-Na'vi)",
"fewi /vtr./", "Chase",
"feyzrr /n./", "Phaser, raygun",
"fkarut /v./", "Peel",
"fkarut v.", "peel",
"fkay /adj./", "Hateful",
"fkeu adj.", "mighty",
"fkew /adj./", "Mighty",
"fkio /n./", "Tetrapteron",
"fkip /adp./", "Up among",
"fko /pn./", "One, they (singular usage) (unspecified agent)",
"fko adj.", "one",
"fkxake /v./", "Itch",
"fkxakewll /n./", "Itch plant",
"fkxen /n./", "Vegetable (food)",
"flefle /n./", "Sol's delight, magnetotrophic plant",
"flew /n./", "Throat",
"flä /vin./", "Succeed",
"fmal /vtr./", "Sustain",
"fmawn /n./", "News, something to report",
"fmawn n.", "news news, something to report",
"fmetok /v./", "Test",
"fmetok n.", "test",
"fmi /vtr./", "Try, attempt",
"fmi v.", "try",
"fnan /vtr./", "Be good at",
"fnawe' /adj./", "Cowardly",
"fnawe'tu /n./", "Coward",
"fnel /n./", "Kind, type",
"fnepe /inter./", "Which kind",
"fngap /n./", "Metal",
"fngapsutxwll /n./", "Metalfollowing plant",
"fnu /v./", "Quiet, be quiet",
"fnu v, c", "quiet quiet (''be quiet!'')",
"fo /pn./", "They",
"fo pn", "they ",
"fpak /v./", "Hold off, suspend action",
"fpak v.", "hold off, suspend action",
"fpe' /vtr./", "Send",
"fpe' v.", "send",
"fpeio /n./", "Challenge (ceremonial)",
"fpeio v.", "challenge challenge (ceremonial)",
"fpi (expression)", "for the sake of",
"fpi /adp./", "For the sake of, for the benefit of",
"fpom /n./", "Wellbeing, peace, happiness",
"fpom n.", "well-being, peace",
"fpomtokx /n./", "Health (physical)",
"fpxafaw /n./", "Medusa",
"fpxafaw n.", "medusa (animal)",
"fpxäkìm /v./", "Enter",
"fpxäkìm v.", "enter",
"fpìl /vtr./", "Think",
"fpìlfya /n./", "Thought pattern, way of thinking",
"fra'u /pn./", "Everything",
"fra'u pn", "everything",
"frakrr /adv./", "Always, all the time",
"fralo /n./", "Every time, every instance, each time",
"frapo /pn./", "Everyone",
"frapo pn", "everyone",
"frato /part./", "Superlative marker than all (behaves like an adp.)",
"fratrr /adv./", "Daily, every day",
"fratseng /adv./", "Everywhere",
"fratxon /adv./", "Every night",
"frawzo /intj./", "All is well, everything is fine or OK",
"frrfen /vtr./", "Visit",
"frrtu /n./", "Guest, visitor",
"frìp /vtr./", "Bite",
"ftang /v./", "Stop",
"ftang v.", "stop ",
"ftawnemkrr /n./", "Past",
"fte /conj./", "So that, in order to",
"fte conj.", "so that ",
"fteke /conj./", "So that not, lest",
"fteke conj.", "so that not, lest ",
"ftem /vtr./", "Pass by (something)",
"ftia /vtr./", "Study",
"ftia v.", "study ",
"ftu /adp./", "From (direction)",
"ftu pr", "from (direction)",
"ftue /adj./", "Easy, simple",
"ftue adj.", "easy",
"ftxavang /adj./", "Passionate",
"ftxey /conj./", "Whether, or",
"ftxey /vtr./", "Choose",
"ftxey v.", "choose ",
"ftxozä /n./", "Celebration, happy occasion",
"ftxì /n./", "Tongue",
"ftxìlor /adj./", "Delicious, good tasting",
"ftxìvä' /adj./", "Bad tasting",
"ftär /adj./", "Left (not right)",
"fu /conj./", "Or",
"fu conj.", "or ",
"fuke /conj./", "Or not",
"fula /pn., sbd./", "That",
"furia /pn., sbd./", "That",
"futa /pn., sbd./", "That",
"fwa /pn., sbd./", "That (subordinate clause marker)",
"fwel /adj./", "Broken",
"fwew /vtr./", "Look for, seek, search",
"fwäkì /n./", "Mantis",
"fwäkìwll /n./", "Mantis orchid",
"fya'o /n./", "Path, way, manner",
"fya'o n.", "path, way ",
"fyape /inter./", "How",
"fyape conj.", "how ",
"fyawìntxu /vin./", "Guide (with dative of thing guided)",
"fyawìntxu n.", "guide",
"fyeyn /adj./", "Ripe, mature, adult",
"fyeyntu /n./", "Adult person",
"fäpa /n./", "Top",
"fì /prefix/", "This",
"fì'u /pn./", "This (thing)",
"fì'u pn", "this (thing)",
"fì'u", "''this, this thing''",
"fìfya /adv./", "This way, like this",
"fìfya pn", "this (this way, like this)",
"fìfya", "''like this''",
"fìkem /pn./", "This (action)",
"fìkem pn", "this (action)",
"fìkem", "''this (action)''",
"fìpo /pn./", "This one (person or thing)",
"fìpo pn", "this (one person or thing)",
"fìtrr /adv./", "Today",
"fìtseng /adv./", "Here, this place",
"fìtseng(e) pn", "here, this place",
"fìtseng(e)", "''here''",
"fìtsenge /adv./", "Here, this place",
"fìtxan /adv./", "So, to such an extent",
"fìtxon /adv./", "Tonight",
"ha /adv./", "So, in that case",
"ha conj.", "so so (or ''in that case'')",
"ha'ngir /n./", "Afternoon",
"hahaw /vin./", "Sleep",
"ham /adj./", "Previous",
"hamalo /adv./", "Last time",
"hametsì /n./", "Leavened bread",
"hangham /vin./", "Laugh",
"hapxì /n./", "Part",
"hapxì n.", "part ",
"hapxìtu /n./", "Member",
"hasey /adj./", "Done, finished",
"hasey adj.", "done, finished",
"hawl /v./", "Prepare",
"hawng /n./", "Overabundance",
"hawngkrr /adv./", "Late",
"hawnu /vtr./", "Protect, shelter",
"hawnu v.", "protect, shelter ",
"hay /adj./", "Next",
"hayalo /adv./", "Next time",
"hek /vin./", "Be curious, odd, strange, unexpected",
"hewne /adj./", "Soft (of an object)",
"heyn /vin./", "Sit",
"hiyìk /adj./", "Funny, strange",
"hiyìk adj.", "funny, strange",
"hol /adj./", "Few",
"holpxay /n./", "Number",
"holpxaype /inter./", "How many",
"hrrap /n./", "Danger",
"hrrap n.", "danger ",
"hu /adp./", "With (accompaniment)",
"hu adj.", "with (accompaniment)",
"hufwa /conj./", "Although",
"hufwe /n./", "Wind",
"hufwe n.", "wind ",
"hultstxem /vtr./", "Hinder",
"hum /v./", "Leave, depart",
"hum v.", "leave, depart ",
"hì'ang /n./", "Insect",
"hì'i /adj./", "Small, little (in size)",
"hì'i adj.", "small ",
"hìkrr /n./", "Second, very short time",
"hìm /adj./", "Small (in quantity)",
"hìmtxampe /inter./", "How much",
"hìmtxan /n./", "Amount",
"hìno /adj./", "Fine, detailed, precise, intricate (of things)",
"hìrumwll /n./", "Puffer plant",
"hìtxoa /intj./", "Excuse me",
"i'en /n./", "Stringed instrument",
"i'en n.", "stringed instrument ",
"ikran /n./", "Banshee",
"ikran n.", "mountain banshee ",
"ikranay /n./", "Forest banshee (Not PF)",
"io /adp./", "Above",
"ioang /n./", "Animal, beast",
"ioang n.", "animal, beast",
"irayo /n., intj./", "Thank you, thanks",
"irayo n. , i", "thank you",
"irayo si /vin./", "Thank, give thanks",
"iveh k'nivi s'di n.", "baby carrier/sling",
"jakesully /n./", "Moron, toruk maktoyu",
"ka /adp./", "Across",
"ka adv.", "across",
"kakrel /adj./", "Blind",
"kali'weya /n./", "Species of poisonous arachnid",
"kalin /adj./", "Sweet",
"kaltxì /intj./", "Hello",
"kaltxì n.", "hello ",
"kaltxì si /v./", "Say hello, greet",
"kame /vtr./", "See, see into, understand, know (spiritual sense)",
"kame v.", "see see (spiritual sense)",
"kan /v./", "Aim (can take subjunctive modal construction)",
"kan'ìn /vtr./", "Focus on, specialize in, be particularly",
"kangay /adj./", "Valid",
"kangay adj.", "valid ",
"kanu /adj./", "Smart, intelligent (for a person)",
"kar /v./", "Teach",
"karyu /n./", "Teacher",
"karyu n.", "teacher",
"kato /n./", "Rhythm",
"kato n.", "rhythm",
"kavuk /n./", "Treachery",
"kavuk si /vin./", "Betray",
"kaw'it /adv./", "At all, not at all (see ke...kaw'it not...at all)",
"kawkrr /adv./", "Never",
"kawkrr adv.", "never ",
"kawng /adj./", "Bad, evil",
"kawng adj.", "bad, evil",
"kawtu /pn./", "Noone",
"kawtu pn", "no one",
"kaym /n./", "Evening (before twilight), late afternoon",
"ke /adv./", "Not",
"ke adv.", "not ",
"ke'aw /adj./", "Divided, torn apart, striferidden",
"ke'u /pn., adv./", "Nothing, nothing at all, not at all",
"ke'u n.", "nothing ",
"kea /adj./", "No (before a noun)",
"kea adj.", "no (before a noun)",
"keftxo /adj., intj./", "Unhappy, upset, 'How sad!'",
"kefyak /part./", "Isn't it?, right?",
"kehe /adv./", "No",
"kehe adv.", "no",
"kelfpomtokx /adj./", "Unhealthy",
"kelku /n./", "Home, house",
"kelku n.", "home ",
"kelku si /vin./", "Live, dwell",
"kelku si v.", "live, dwell ",
"keltsun /adj./", "Impossible",
"kem /n./", "Thing (action), deed",
"kem si /vin./", "Do",
"kemlì'u /n./", "Verb",
"kemlì'uvi /n./", "Infix",
"kempe /inter./", "What (action)",
"kempe pn", "what what (action)",
"keng /adv./", "Even, so much as",
"kenong or [ˈkɛ.n·oŋ] /v./", "Model, represent, exemplify (ii)",
"kenong v.", "model, represent, exemplify ",
"kenten /n./", "Fan lizard",
"kerusey /adj./", "Dead",
"kerusey adj.", "dead ",
"keteng /adj./", "Different",
"ketuwong /n./", "Alien",
"ketuwong n.", "alien ",
"kew /num./", "Zero",
"kewong /adj./", "Alien",
"kewong n.", "alien ",
"key /n./", "Face",
"keyawr /adj./", "Incorrect, not right",
"keye'ung /n./", "Insanity",
"keye'ung n.", "insanity",
"ki /conj./", "But rather, but instead",
"kifkey /n./", "World (physical, solid)",
"kifkey n.", "world world (physical, solid)",
"kilvan /n./", "River",
"kin /vtr./", "Need",
"kin v.", "need ",
"kinam /n./", "Leg",
"kinam n.", "leg",
"kinamtil /n./", "Knee",
"kinamtil n.", "knee",
"kinä /num./", "Seven",
"kinä n. , adj.", "seven ",
"kip /adp./", "Among",
"kip pr", "among ",
"kive /adj./", "Seventh (ordinal)",
"kllfriyo' v, c", "be responsible ",
"kllfro' /v./", "Be responsible",
"kllkulat /v./", "Dig up",
"kllkulat v.", "dig up",
"kllkxem /v./", "Stand",
"kllkxem v.", "stand",
"kllkä /v./", "Descend",
"kllpa /n./", "Bottom",
"kllpxiwll /n./", "Lionberry",
"kllpxìltu /n./", "Territory",
"kllpxìltu n.", "territory",
"kllte /n./", "Ground",
"kllte n.", "ground ",
"klltseng /n./", "Position",
"kllvawm /adj./", "Brown",
"ko /part./", "Solicit agreement",
"koak /adj./", "Old, aged (for living things)",
"kop /adv./", "Too, also",
"koren /n./", "Rule, guideline",
"krr /n./", "Time",
"krr n.", "time ",
"krrnekx /v./", "Take/consume time (ii)",
"krrnekx v.", "take/consume time",
"krrpe /inter./", "When",
"krrpe adv.", "when ",
"ku'up /adj./", "Heavy (physical weight)",
"kunsìp /n./", "Gunship",
"kunsìp n.", "gunship ",
"kurakx /v./", "Drive out",
"kurakx v.", "drive out ",
"kxa /n./", "Mouth",
"kxam /n./", "Middle, midpoint",
"kxam n.", "middle, midpoint",
"kxamlä /adp./", "Through (via the middle of)",
"kxamtrr /n./", "Midday, noon",
"kxamtrrmaw /n./", "The time immediately after noon, early",
"kxamtseng /n./", "Center, place in the middle",
"kxamtseng n.", "center (or place in the middle) ",
"kxamtxomaw /n./", "After midnight",
"kxamtxon /n./", "Midnight",
"kxangangang /intj./", "Boom (onomatopoeic)",
"kxangangang n.", "boom ",
"kxanì /adj./", "Forbidden",
"kxanì adj.", "forbidden",
"kxawm /adv./", "Perhaps, maybe",
"kxawm adv.", "perhaps, maybe ",
"kxayl /adj./", "High",
"kxaylte /n./", "Cillaphant",
"kxener /n./", "Smoke",
"kxener n.", "species of fruit or vegetable",
"kxetse /n./", "Tail",
"kxetse n.", "tail",
"kxeyey /n./", "Error, mistake",
"kxitx /n./", "Death",
"kxll /n./", "Charge, running attack",
"kxll si /vin./", "Charge",
"kxu /n./", "Harm",
"kxuke /adj./", "Safe",
"kxutu /n./", "Enemy",
"kä /vin./", "Go",
"kä v.", "go",
"kä'ärìp /vtr./", "Push",
"kämakto /v./", "Ride out",
"kämakto v.", "ride out ",
"käpxì /n./", "Rear (part or section)",
"käsatseng /adv./", "Out there",
"käteng /vin./", "Spend time with, hang out with",
"kì'ong /adj./", "Slow",
"kì'ong n.", "species of fruit or vegetable",
"kìm /v./", "Spin",
"kìm v.", "spin ",
"kìng /n./", "Thread",
"kìng n.", "thread",
"kìte'e /n./", "Service",
"kìte'e n.", "service ",
"kìyevame n.", "good-bye good-bye, see you again soon",
"lahe /adj./", "Other, else",
"lahe adj, pn", "other",
"lam /vin./", "Seem, appear",
"lam v.", "seem, appear ",
"lapo /pn./", "Other one (person or thing)",
"lapo pn", "other one (person or thing)",
"laro /adj./", "Clean",
"latem /vin./", "Change",
"latem v.", "change ",
"latsi /v./", "Keep up with someone",
"law /adj./", "Clear, certain",
"law adj.", "clear, certain ",
"law si /vin./", "Make clear",
"lawk /vtr./", "Discourse on, talk about, say something concerning",
"layompin /n./", "Black",
"layon /adj./", "Black",
"leNa'vi /adj./", "Having to do with the Na'vi, the People",
"lefkrr /adj./", "Current",
"lefngap /adj./", "Metallic",
"lefpom /adj./", "Happy, peaceful, joyous (not for people), pleasant",
"lefpomtokx /adj./", "Healthy",
"lehawng /adj./", "Excessive",
"lehawngkrr /adj./", "Late",
"lehrrap /adj./", "Dangerous",
"lehrrap adj.", "dangerous",
"lek /v./", "Heed, obey",
"lekin /adj./", "Necessary",
"lekoren /adj./", "Lawlike",
"lekye'ung /adj./", "Insane, crazy",
"lemweypey /adj./", "Patient",
"len /vin./", "Happen, occur",
"leno /adj./", "Thorough, detailorientated (of a person)",
"lenomum /adj./", "Curious",
"lertu /n./", "Colleague",
"lertu n.", "colleague",
"lerìk /adj./", "Leafy",
"lesar /adj./", "Useful",
"letam /adj./", "Sufficient",
"letokx /adj./", "Bodily, physical",
"letrr /adj./", "Daily",
"letrrtrr /adj./", "Ordinary",
"letsranten /adj./", "Important",
"letsunslu /adj./", "Possible",
"lew /n./", "Cover, lid",
"lew si /vin./", "Cover",
"leye'krr /adj./", "Early",
"leyn /vtr./", "Repeat, do again",
"lok /adp./", "Close to",
"lok /v./", "Approach",
"lok adj.", "close close to",
"lonataya /n./", "Medusa",
"lonu /vtr./", "Release, let go",
"lonu v.", "release, let go ",
"lor /adj./", "Beautiful, pleasant to the senses (for things or parts",
"loreyu /n./", "Helicoradian, beautiful spiral",
"lrrtok /n./", "Smile",
"lrrtok si /vin./", "Smile",
"lrrtok v.", "smile ",
"lu /vin., svin./", "Be, am, is, are",
"lu v.", "be (am, is, are)",
"luke /adp./", "Without",
"lumpe /inter./", "Why",
"lumpe adv.", "why",
"lun /n./", "Reason",
"lì'fya /n./", "Language",
"lì'fyaolo' /n./", "Language group, language users",
"lì'fyavi /n./", "Expression, bit of language",
"lì'u /n./", "Word",
"lì'u n.", "word",
"lì'upam /n./", "Accent, pronunciation",
"lì'upe /inter./", "What (word, utterance)",
"lìm /svin./", "Far, be far",
"lìng /vin./", "Float in the air, hover",
"ma /part./", "O (vocative marker)",
"makto /v./", "Ride",
"makto v.", "ride ",
"matsa /n./", "Matsa, crackers",
"maw /adp./", "After (time)",
"mawey /adj./", "Calm",
"mawey adj.", "calm ",
"maweypey /svin./", "Be patient (ii)",
"mawkrr /adv./", "After, afterwards",
"me'em /adj./", "Harmonious",
"mefo /pn./", "They, those two",
"mefo pn", "they (those two) ",
"mekre /n./", "Supplies",
"melo /adv./", "Twice",
"menari /n./", "Eyes (two)",
"menari n.", "eyes (two)",
"meoauniaea /n./", "Harmony, living at one with nature",
"meuia /n./", "Honor (honour)",
"meuia n.", "honor",
"meyp /adj./", "Weak",
"meyp adj.", "weak",
"mi /adv./", "Yet, still, as before",
"mikyun /n./", "Ear",
"mikyun n.", "ear ",
"mip /adj./", "New",
"mllte /v./", "Agree",
"mllte v.", "agree",
"moe /pn./", "We two, us two (exclusive)",
"moe pn", "we we two (exclusive)",
"mok /vtr./", "Suggest",
"mokri /n./", "Voice",
"mokri n.", "voice",
"mowan /adj./", "Pleasing, enjoyable (physically, sexually)",
"mrr /num./", "Five",
"mrrve /adj./", "Fifth (ordinal)",
"muiä /adj./", "Proper, fair, right, justified",
"muiä adj.", "proper, fair, right ",
"mulpxar /n./", "Roosterhead plant",
"mun'i /v./", "Cut",
"mun'i v.", "cut",
"mune /num./", "Two",
"mune n. , adj.", "two ",
"munge /vtr./", "Take, bring",
"munge v.", "take, bring",
"mungwrr /adp./", "Except",
"muntxa /adj./", "Mated, married",
"muntxa adj.", "mated ",
"muntxa si /vin./", "Mate (with someone), marry",
"muntxatan /n./", "Husband, male spouse",
"muntxate /n./", "Wife, female spouse",
"muntxatu /n./", "Spouse",
"muve /adj./", "Second (ordinal)",
"muwìntxu /vtr./", "Introduce, present",
"mäkxu /vtr./", "Interrupt, throw out of harmonious balance",
"mì /adp./", "In, on",
"mì pr", "in ",
"mìfa or [mɪ.ˈfa] /n., adv./", "Inside",
"mìkam /adp./", "Between",
"mìn /v./", "Turn",
"mìn adj.", "turn ",
"mìnyu /n./", "Turner",
"mìnyu /n./", "Turner, twisted lily",
"mìso /adv./", "Away (position)",
"mìso adv.", "away (position)",
"na /adp./", "Like, as",
"na adv., conj", "like, as ",
"na'rìng /n./", "Forest",
"na'rìng n.", "forest ",
"naer /n./", "Drink, something able to be drunk",
"nafì'u /adj./", "Such",
"nang (expression)", "particle for surprise or exclamation",
"nang /part./", "Surprise, exclamation, encouragement (mirative)",
"nantang /n./", "Viperwolf Caniferratus costatus, striped armored",
"nantang n.", "viperwolf Caniferratus costatus or striped armored wolf.",
"nari /n./", "Eye",
"nari n.", "eye ",
"nari si /vin./", "Watch out, be careful",
"nari si c, v", "watch out, be careful",
"natkenong /conj./", "For example, as an example",
"nawm /adj./", "Great, noble",
"nawm adj.", "great, noble",
"nawmtu /n./", "Great person",
"nayn /n./", "The symbol 9 (not the value nine)",
"ne /adp./", "To, towards (direction)",
"ne adv.", "to (direction)",
"ne kllte /intj./", "Get down",
"ne kllte! (expression)", "get down! (literally, ''to the ground!'')",
"ne'ìm /adv./", "Back (direction)",
"ne'ìm adv.", "back (direction)",
"nefä /adv./", "Up (direction)",
"nekll /adv./", "Down (direction)",
"nekx /vtr./", "Burn, consume",
"nekx v.", "burn, consume ",
"nemfa /adp./", "Into, inside",
"neto /adv./", "Away (direction)",
"neto adv.", "away (direction)",
"netrìp /adv./", "Luckily, happily",
"neu v.", "want ",
"new /vtr./", "Want (with subjunctive verb)",
"newomum /vin./", "Be curious, want to know",
"neympin /n./", "Light color",
"neyn /adj./", "Light colors, shades of white",
"nga /pn./", "You",
"nga pn", "you ",
"ngatsyìp /pn./", "Little you, you little",
"ngawng /n./", "Worm",
"ngawng n.", "worm",
"ngay /adj./", "True",
"ngay adj.", "true",
"ngaytxoa /intj./", "Sorry, my apologies (acknowledgment of",
"ngenga /pn./", "You (honorific (honourific) form)",
"ngenga pn", "you you (honorific form)",
"ngeyn /adj./", "Tired",
"ngian /adv./", "However",
"ngim /adj./", "Long (physical length)",
"ngop /v./", "Create",
"ngop v.", "create",
"ngopyu /n./", "Creator",
"ngrr /n./", "Root",
"ngrrpongu /n./", "Grassroots movemenet",
"ngul /adj./", "Grey, drab",
"ngulpin /n./", "Grey",
"nguway /n./", "Howl, viperwolf cry",
"ngäng /n./", "Stomach",
"ngäzìk /adj./", "Difficult, hard",
"nikre /n./", "Hair",
"nitram /adj./", "Happy (of people)",
"niä /vtr./", "Grab",
"niä v.", "grab ",
"nokx /vtr./", "Give birth to",
"nong /v./", "Follow, proceed after",
"nulkrr /adv./", "Longer (time)",
"nulkrr adj.", "longer longer (time)",
"nulnew /v./", "Prefer (ii)",
"nume /v./", "Learn",
"nume v.", "learn ",
"numeyu /n./", "Student",
"numtseng /n./", "School",
"numtsengvi /n./", "Classroom, division of a school",
"näk /vtr./", "Drink",
"nì'aw /adv./", "Only",
"nì'aw adj.", "only ",
"nì'awtu /adv./", "Alone (as one person)",
"nì'awtu adj.", "alone alone (as one person)",
"nì'awve /adv./", "First",
"nì'awve adj.", "first",
"nì'eng /adv./", "Equally, on the same level",
"nì'eoio /adv./", "Ceremoniously",
"nì'eveng /adv./", "Like a child, immaturely",
"nì'eyng /adv./", "Back, in response, in answer",
"nì'i'a /adv./", "Finally, at long last",
"nì'it /adv./", "A bit, a small amount (abstract)",
"nì'it n.", "bit a small amount",
"nì'o' /adv./", "In a manner which is enjoyable, enjoyably",
"nì'ul /adv./", "More",
"nì'ul adj.", "more ",
"nìFranse /adv./", "French, in French",
"nìNa'vi /adv./", "Like the Na'vi, Na'vily",
"nìToitsye /adv./", "German, Deutsch",
"nìawnomum /adv./", "As you know, as is known",
"nìayoeng /adv./", "Like us, as we do",
"nìfkrr /adv./", "Lately, currently",
"nìftue /adv./", "Easily",
"nìftue adv.", "easily",
"nìftxavang /adv./", "Passionately, with all heart",
"nìftxavang adv.", "passionately, with all heart ",
"nìfya'o /adv./", "In a manner",
"nìfyeyntu /adv./", "Like an adult, maturely",
"nìhawng /adv./", "Too, excessively",
"nìhawng adv.", "too too, excessively",
"nìhay /adv./", "Next",
"nìhek /adv./", "Strangely, oddly",
"nìk'ong /adv./", "Slowly",
"nìkanu /adv./", "Intelligently, in a smart way",
"nìkeftxo /adv./", "Unfortunately, sadly",
"nìlaw /adv./", "Clearly",
"nìlkeftang /adv./", "Continuously, incessantly, without stopping",
"nìltsan /adv./", "Well",
"nìltsan adv.", "well ",
"nìmun /adv./", "Again",
"nìmun adv.", "again",
"nìmwey /adv./", "Calmly, peacefully",
"nìmweypey /adv./", "Patiently",
"nìn /vtr./", "Look at",
"nìn v.", "look look (at)",
"nìngay /adv./", "Truly",
"nìngay adv.", "truly ",
"nìno /adv./", "In detail, expansively, thoroughly",
"nìnäk /adv./", "By drinking, in a liquid way",
"nìprrte' /adv./", "Pleasurably, welcome (assumed zola'u),",
"nìpxi /adv./", "Especially, pointedly, unambiguously",
"nìpxim /adv./", "Erectly, rightly",
"nìrangal /adv./", "Wish (contrary to fact, with perfect or",
"nìsti /adv./", "Angrily",
"nìsung /adv./", "Besides, additionally, furthermore",
"nìswey /adv./", "Optimally, best",
"nìsyayvi /adv./", "By chance or coincidence",
"nìsyen /adv./", "Lastly",
"nìtam /adv./", "Enough (after an adjective)",
"nìtam adj.", "enough ",
"nìteng /adv./", "Too, also, as well, likewise",
"nìtengfya /adv./", "As, same way as (similar action)",
"nìtrrtrr /adv./", "On a daily basis, regularly",
"nìtut /adv./", "Continually",
"nìtut adv.", "continually",
"nìtxan /adv./", "Much (abstract), very",
"nìtxan adj.", "much",
"nìwin /adv./", "Fast",
"nìwin adj.", "fast ",
"nìwotx /adv./", "All (of), in toto, completely",
"nìwotx a", "all (all of, completely)",
"nìwä /adv./", "On the contrary, conversely",
"nìzawnong /adv./", "Safely",
"oe /pn./", "I, me",
"oe pn", "I",
"oeng /pn./", "We two, us two (dual inclusive), you and I",
"oeng pn", "we two (you and I)",
"oetsyìp /pn./", "Little me, little I",
"oeyk /n./", "Cause",
"oeyktìng /v./", "Explain (why) (ii)",
"ohakx /adj./", "Hungry",
"ohe /pn./", "I (deferential or ceremonial form)",
"ohe pn", "I (deferential or ceremonial form)",
"olo' /n./", "Clan",
"olo' n.", "clan",
"olo'eyktan /n./", "Clan leader",
"olo'eyktan n.", "clan leader ",
"omum /vtr./", "Know (note infix)",
"omum v.", "know",
"ontu /n./", "Nose",
"ontu n.", "nose",
"oìsss /intj./", "Angry snarl, 'watch it!'",
"pa'li /n./", "Direhorse",
"pa'li n.", "Direhorse",
"pa'liwll /n./", "Direhorse pitcher plant",
"pa'o /n./", "Side",
"pak (expression)", "particle for surprise or exclamation",
"pak /part./", "Disparagement",
"palulukan /n./", "Thanator",
"palulukan n.", "Thanator Dry Mouth Bringer of Fear (Thanator)",
"pam /n./", "Sound",
"pam n.", "sound",
"pamrel /n./", "Writing",
"pamrel si /vin./", "Write",
"pamrelfya /n./", "Spelling",
"pamtseo /n./", "Music",
"pamtseo n.", "music",
"pamtseotu /n./", "Musician",
"pamtseowll /n./", "Cat ear, music plant",
"pate /v./", "Get to a place, arrive",
"pawm /v./", "Ask",
"pawm v.", "ask ",
"pay /n./", "Water, liquid",
"payfya /n./", "Stream",
"payoang /n./", "Fish",
"paywll /n./", "Water plant, dapophet",
"pe /affix/", "Inter. marker",
"pe pn. , adv.", "what what (before a noun)",
"pe'un /vtr./", "Decide",
"pefnel /inter./", "Which kind",
"pefya /inter./", "How",
"pehem /inter./", "What (action)",
"pehem pn, adv", "what what (action)",
"pehem, kempe", "''what? which action?''",
"pehrr /inter./", "When",
"pehrr adv.", "when ",
"pehrr, krrpe", "''when?''",
"pelun /inter./", "Why",
"pelun adv.", "why",
"pelun, lumpe", "''why?''",
"pelì'u /inter./", "What (word, utterance)",
"peng /vtr./", "Tell",
"peng v.", "tell",
"penghrrap /n./", "Binary sunshine, fringed lamp",
"peseng /inter./", "Where",
"peseng adv.", "where ",
"peseng, tsengpe", "''where?''",
"pesu /inter./", "Who",
"pesu pn", "who",
"pesu, tupe", "''who?''",
"peu /inter./", "What (thing)",
"peu pn, adv", "what what (thing)",
"pewn /n./", "Neck",
"pey /v./", "Wait, wait for",
"pey c, v", "wait ",
"peyfa adv.", "how",
"peyfa, fyape", "''how?''",
"peú, 'úpe", "''what? which thing?''",
"piak /adj./", "Open",
"piak si /vin./", "Open",
"pil /n./", "Facial stripe",
"pizayu /n./", "Ancestor",
"pizayu n.", "ancestor",
"plltxe /v./", "Speak",
"plltxe v.", "speak ",
"po /pn./", "He, she",
"po pn", "he, she",
"poan /pn./", "He (no plural form: use (ay)fo)",
"poan pn", "he ",
"poe /pn./", "She (no plural form: use (ay)fo)",
"poe pn", "she ",
"polpxay /inter./", "How many",
"pom /v./", "Kiss",
"pongu /n./", "Group of people, party",
"pongu pn", "group of people, party",
"prrkxentrrkrr /n./", "Day time smoking pleasure, vibrating",
"prrnen /n./", "Infant, baby",
"prrnesyul /n./", "Bud",
"prrte' /adj./", "Pleasurable (of an activity)",
"prrwll /n./", "Moss",
"puk /n./", "Book",
"pukap /num./", "Six",
"puktsyìp /n./", "Pamphlet, booklet",
"pum /pn./", "Possession, thing possessed (dummy pronoun for modified",
"puve /adj./", "Sixth (ordinal)",
"pxan /adj./", "Worthy",
"pxan adj.", "worthy",
"pxasul /adj./", "Fresh, appealing as food",
"pxasul adj.", "fresh fresh, appealing as food",
"pxasìk /intj./", "Screw that!, no way! (vulgar)",
"pxaw /adp./", "Around",
"pxawpa /n./", "Perimeter, circumference, border",
"pxay /adj./", "Many",
"pxay adj, pn", "many ",
"pxayzekwä /n./", "Spiny whips",
"pxel /adp./", "Like, as",
"pxel adv.", "like, as",
"pxelo /adv./", "Thrice, three times",
"pxey /num./", "Three",
"pxeyve /adj./", "Third (ordinal)",
"pxi /adj./", "Sharp",
"pxi adj.", "sharp",
"pxim /adj./", "Erect, upright",
"pximaw /adp./", "Right after",
"pxir /n./", "Beer",
"pxiset /adv./", "Right now",
"pxisre /adp./", "Right before",
"pxiswawam /adv./", "Just a moment ago",
"pxiswaway /adv./", "In just a second from now",
"pxiut /n./", "Razor palm, sharp tree",
"pxiwll /n./", "Hermit bud plant",
"pxiye'rìn /adv./", "Immediately (not as soon as pxiswaway)",
"pxor /vin./", "Explode",
"pxorna' /n./", "Episoth, exploding seed",
"pxorna'lor /n./", "Sari, beautiful exploding seed plant",
"pxorpam /n./", "Ejective consonant",
"pxun /n./", "Arm",
"pxun n.", "arm ",
"pxuntil /n./", "Elbow",
"pxuntil n.", "elbow",
"pxìm /adv./", "Often",
"pähem /vin./", "Arrive",
"pähem v.", "arrive ",
"pängkxo /vin./", "Chat, converse, have a conversation",
"pängkxoyu /n./", "Chatter, converser",
"pängkxoyu lekoren /n./", "Lawyer",
"pänu /n./", "Promise",
"pänutìng /vtr./", "Promise (a thing to someone) (ii)",
"pänutìng v.", "promise (a thing to someone) promise (a thing to someone)",
"päsketpol /n./", "Basketball",
"pätsì /n./", "Badge",
"pätsì n.", "badge",
"pìlok /n./", "Blog",
"pìmtxan /inter./", "How much",
"pìwopx /n./", "Cloud",
"ral /n./", "Meaning",
"ral n.", "meaning",
"ralpeng /v./", "Interpret (ii)",
"ralpeng v.", "interpret",
"ram /n./", "Mountain",
"ramtsyìp /n./", "Hill",
"ramunong /n./", "Well",
"rangal /v./", "Wish",
"rawke /intj./", "Alarm cry, call to defense",
"rawke n.", "alarm cry",
"rawp /n./", "Bladder polyp",
"re'o /n./", "Head",
"rel /n./", "Image, picture",
"reltseo /n./", "Visual art",
"reltseotu /n./", "Artist",
"reng /adj./", "Shallow (physically)",
"renu /n./", "Pattern",
"renu n.", "pattern ",
"rewon /n./", "Morning",
"rey /vin./", "Live",
"rey v.", "live ",
"rey'eng /n./", "The Balance of Life",
"reypay /n./", "Blood",
"rikx /vin./", "Move, shift position",
"rikx v.", "move, shift position",
"rim /adj./", "Yellow",
"rim adj.", "yellow ",
"rimpin /n./", "Yellow",
"rina' /n./", "Seed",
"rina' n.", "seed ",
"riti /n./", "Stingbat",
"riti n.", "stingbat",
"ro /adp./", "At (locative)",
"rofa /adp./", "Beside, alongside",
"rol /v./", "Sing",
"rol v.", "sing ",
"rolun /intj./", "Eureka! I've found it!",
"ronsem /n./", "Mind",
"ronsem n.", "mind",
"rum /n./", "Ball",
"rumut /n./", "Ball tree",
"run /vtr./", "Find, discover",
"rusey /adj., n./", "Alive, living, living thing",
"rutxe /intj./", "Please",
"rutxe v.", "please ",
"rä'ä /part./", "Do not (for negative imperatives, commands only)",
"rä'ä v.", "do not negative (do not)",
"rìk /n./", "Leaf",
"rìkean /adj./", "Leaf green",
"sa'nok /n./", "Mother",
"sa'nok n.", "mother",
"sa'nu /n./", "Mum, mommy (affectionate form of)",
"sa'nu n.", "mommy",
"sa'nutsyìp /n./", "Little mommy (used for young girls)",
"sa'sem /n./", "Parents (not singular)",
"saa /intj./", "Threatening cry",
"salew /v./", "Proceed, go",
"san /adv./", "Saying, quote",
"san n.", "saying; quote",
"sar /vtr./", "Use",
"sat /pn./", "That",
"sat pn", "that (after ftu only)",
"sau /intj./", "Exclamation upon exertion, urgh",
"sayrìp /adj./", "Handsome, good looking (normally used of men)",
"sekrr /adv./", "Present",
"sempu /n./", "Daddy (affectionate form of)",
"sempu n.", "daddy",
"sempul /n./", "Father",
"sempul n.", "father",
"set /adv./", "Now",
"set adv.", "now",
"sevin /adj./", "Pretty (primarily of females, for people only)",
"sevin adj.", "pretty ",
"seykxel /adj./", "Strong (emotionally, spiritually, not",
"seyri /n./", "Lip",
"seyri n.", "lip",
"seze /n./", "Blue flower",
"seze n.", "blue flower",
"si //", "Auxiliary verb, postpositional nonbound verb do, make",
"si v.", "do, make",
"sim /svin./", "Near, be near",
"ska'a /vtr./", "Destroy",
"ska'a v.", "destroy",
"skepek /adj./", "Formal",
"skien /adj./", "Right (not left)",
"skxakep /adj., adv./", "Probable, probably",
"skxawng /n./", "Moron, idiot",
"skxawng n.", "moron",
"skxaypxe /n./", "Skype",
"skxom /n./", "Chance, opportunity",
"sleyku /vtr./", "Produce",
"slu /vin./", "Become (noun predicate with ne in ambiguous constructions)",
"slu v.", "become ",
"slä /conj./", "But",
"slä conj.", "but ",
"smaoe /n./", "Phalanxia, heavily thorned plant",
"smar /n./", "Prey, hunted thing",
"smon /vin./", "Be familiar, be known (with dative)",
"sngap /vtr./", "Sting",
"sngel /n./", "Garbage, trash, rubbish",
"sngeltseng /n./", "Rubbish place, garbage dump",
"sngukx /n./", "Grub plant",
"sngä'i /vin./", "Begin, start (with subjunctive)",
"sngä'i v.", "begin, start",
"sngä'ikrr /n./", "Beginning, starting time",
"sngä'ikrr n.", "beginning, start time",
"sngä'iyu /n./", "Beginner",
"sno /pn./", "his own, her own, its own (reflexive, genitive form sneyä)",
"snumìna /adj./", "Dim (of a person)",
"snumìna adj.", "dim dim (of a person)",
"soaia /n./", "Family (irregular genitive form soaiä)",
"sok /adj./", "Recent",
"som /adj./", "Hot",
"som adj.", "hot",
"somtìlor /n./", "Popsicle, hot beauty",
"sop /vin./", "Travel",
"sopyu /n./", "Traveller",
"spaw /v./", "Believe",
"spe'e /vtr./", "Capture",
"spe'e v.", "capture",
"spe'etu /n./", "Captive",
"spe'etu v.", "captive",
"speng /v./", "Restore",
"spule /vtr./", "Propel",
"spuwin /adj./", "Old (not for people), former",
"spxam /n./", "Mushroom, fungus",
"spxin /adj./", "Sick",
"spä /v./", "Jump",
"srak /part./", "Inter. marker for yes or no questions",
"srak(e) ", "marker for yes-no questions",
"srake /part./", "Inter. marker for yes or no questions",
"sran /adv., intj./", "Yes (colloquial)",
"srane /adv., intj./", "Yes",
"srane adv.", "yes",
"sraw /adj./", "Painful",
"sre /adp./", "Before (time)",
"sre' /n./", "Tooth",
"srekamtrr /n./", "The time before noon",
"srekamtxon /n./", "Before midnight",
"srekrr /adv./", "Before, already, ahead of time",
"srese'a /v./", "Prophetize, prophesize, prophesy",
"sresrr'ong /n./", "Before dawn",
"sreton'ong /n./", "Dusk, evening before sunset",
"sreu v.", "dance ",
"srew /vin./", "Dance",
"srung /n./", "Help, assistance",
"srung n.", "help help, assistance",
"srung si /vin./", "Help",
"starsìm /vtr./", "Gather, collect",
"stawm /vtr./", "Hear",
"steftxaw /vtr./", "Examine, check",
"steftxaw v.", "examine ",
"steyki /vtr./", "Anger, make someone angry",
"sti /vin./", "Anger (intransitive), be angry",
"sto /v./", "Refuse (to do something)",
"stum /adv./", "Almost",
"stum adv.", "almost",
"stxeli /n./", "Gift",
"stxong /adj./", "Strange, unfamiliar, unknown",
"stä'nì /vtr./", "Catch",
"sulìn /vin./", "Be busy (positive sense), be engrossed in",
"sung /vtr./", "Add",
"sunu /vin./", "Be pleasing or likeable, bring enjoyment",
"sutx /vtr./", "Track, follow, lock up",
"sutx v.", "track, lock up",
"swaw /n./", "Moment",
"swaw n.", "moment",
"swawtsyìp /n./", "Litte moment, second",
"swey /adj./", "Best",
"swirä /n./", "Creature",
"swirä n.", "creature ",
"swizaw /n./", "Arrow",
"swizaw n.", "arrow ",
"swok /adj./", "Sacred",
"swok n.", "sacred",
"swotu /n./", "Sacred place",
"swotu n.", "sacred place ",
"syaksyuk /n./", "Prolemuris",
"syaw /vin./", "Call, name",
"syaw v.", "call",
"syay /n./", "Fate",
"syayvi /n./", "Luck, chance",
"syen /adj./", "Last, final",
"syep /vtr./", "Trap",
"syeptute /n./", "Hyneman, person trapper",
"syo /adj./", "Light (physical weight), lightweight",
"syulang /n./", "Flower",
"syuve /n./", "Food (collective noun, cannot be pluralised)",
"syä'ä /adj./", "Bitter",
"säfpìl /n./", "Idea",
"sänume /n./", "Teaching, instruction",
"sänume n.", "teaching, instruction ",
"sänumvi /n./", "Lesson",
"säspxin /n./", "Disease, sickness, illness",
"säspxintsyìp /n./", "Minor ailment",
"säsulìn /n./", "Hobby, pleasureyielding activity",
"säzärìp /n./", "Face lead, rein",
"sì /conj./", "And (connects two things, can be attached as sì: for",
"sì conj.", "and",
"sìk /adv./", "Unquote",
"sìk v.", "unquote",
"sìlpey /vin./", "Hope (with tsnì for thing hoped, unless in",
"sìlronsem /adj./", "Clever, smart (thing)",
"sìlronsem adj.", "clever (thing)",
"sìltsan /adj./", "Good (of its kind), well done",
"sìltsan adj.", "good ",
"sìn /adp./", "On, onto",
"ta /adp./", "From (various uses)",
"ta pr", "from from (various uses)",
"ta'em /adv./", "From above",
"ta'em v.", "from above ",
"ta'leng /n./", "Skin",
"ta'lengean /adj./", "Skin blue",
"tafkip /adp./", "From up among",
"tafral /adv./", "Therefore, because of that",
"takip /adp./", "From among",
"takuk /vtr./", "Strike",
"takuk v.", "strike ",
"talioang /n./", "Sturmbeest",
"talioang n.", "sturmbeest",
"talun /conj./", "Because, from the reason",
"taluna /conj./", "Because, from the reason",
"tam /vin., intj./", "That will suffice, that will do, OK",
"tam tam /intj./", "Calm, be content, there there",
"tam v.", "suffice suffice, ''do''",
"tangek /n./", "Trunk (of a tree)",
"tangek n.", "trunk trunk (of a tree)",
"tanhì /n./", "Star, bioluminescent freckle",
"tanhì n.", "star ",
"taron /vtr./", "Hunt",
"taron v.", "hunt ",
"taronyu /n./", "Hunter",
"taronyu n.", "hunter ",
"taronyutsyìp /n./", "Little hunter",
"tatep /vtr./", "Lose track, lose awareness of something",
"tatlam /adv./", "Apparently",
"tautral /n./", "Sky tree",
"taw /n./", "Sky",
"taw n.", "sky",
"taweyk /conj./", "Because, based on the cause",
"taweyka /conj./", "Because, based on the cause",
"tawng /vin./", "Duck, dive",
"tawng n.", "duck ",
"tawng v.", "dive ",
"tawsìp /n./", "Skyship",
"tawtsngal /n./", "Panopyra, sky cup",
"te /part./", "Used in full names",
"te pa", "particle used in full names",
"tel /vtr./", "Receive",
"telem /n./", "Cord",
"telem n.", "cord ",
"tem /vin./", "Shoot",
"teng /adj./", "Same, equal",
"tengfya /conj./", "As, same way as (situational similarity)",
"tengfya adj, conj", "as as (= same way as)",
"tengkrr /conj./", "While, same time as",
"tengkrr conj., pr", "while (= same time as)",
"teri /adp./", "About, concerning",
"terkup /vin./", "Die",
"terkup v.", "die ",
"teswotìng /v./", "Grant (ii)",
"teswotìng v.", "grant",
"tete /adj./", "Dull (as a blade)",
"tewti /intj./", "Wow, expression of surprise and pleasure",
"teya /adj./", "Full",
"teya adj.", "full",
"teya si /vin./", "Fill (with dative of thing filled)",
"teylu /n./", "Beetle larva",
"teylu n.", "beetle larva(e)",
"teyr /adj./", "White",
"teyrpin /n./", "White",
"til /n./", "Joint, hinge",
"til n.", "joint, hinge ",
"tirea /n./", "Spirit",
"tirea n.", "spirit ",
"tireafya'o /n./", "Spirit path",
"tireafya'o n.", "spirit path ",
"tireaioang /n./", "Spirit animal",
"tireaioang n.", "spirit animal ",
"tireapängkxo /v./", "Commune",
"to /part./", "Comparative marker than (behaves like an adp.)",
"to conj.", "than; comparative mark ",
"tok /vtr./", "Be at, occupy a space",
"tok v.", "be at, occupy a space",
"toktor /n./", "Doctor",
"toktor n.", "doctor",
"tokx /n./", "Body",
"tokx n.", "body",
"tolel /intj./", "Eureka! I found it! I understand!",
"toltem /vtr./", "Shoot",
"tompa /n./", "Rain",
"tompa n.", "rain ",
"tompawll /n./", "Geode, rain plant",
"tor /adj./", "Last, ultimate, terminal",
"toruk /n./", "Great leonopteryx, last shadow",
"toruk makto /n./", "Toruk rider",
"toruk n.", "great leonopteryx last shadow (great leonopteryx)",
"torukspxam /n./", "Octoshroom, great leonopteryx fungus",
"trr /n./", "Day",
"trr n.", "day",
"trr'awve /n./", "Sunday",
"trr'ong /n./", "Dawn, sunrise",
"trr'ongmaw /n./", "Dawn after sunrise",
"trram /adv./", "Yesterday",
"trray /adv./", "Tomorrow",
"trrkive /n./", "Saturday",
"trrmrrve /n./", "Thursday",
"trrmuve /n./", "Monday",
"trrpeve /inter./", "Which day (derived from trr day and pe",
"trrpuve /n./", "Friday",
"trrpxeyve /n./", "Tuesday",
"trrtsìve /n./", "Wednesday",
"trrtxon /n./", "The day and night cycle of Pandora",
"tsa /prefix/", "That",
"tsa'u /dem./", "That (thing)",
"tsa'u pn", "that that (thing",
"tsa'u", "''that, that thing''",
"tsafya /pn./", "That way, like that",
"tsahey /intj./", "Expression of warning or frustration,",
"tsaheyl si /vin./", "Bond with, establish a neural connection",
"tsaheylu /n./", "Bond (neural connection)",
"tsakem or [t͡sa.ˈkɛm] /dem./", "That (action)",
"tsakem pn", "that that (action)",
"tsakem", "''that (action)''",
"tsakrr /dem./", "Then, at that time",
"tsakrr pn", "then then, at that time",
"tsakrr", "''then''",
"tsakrrvay /adv./", "Until then, in the meantime",
"tsal /pn./", "That, it (transitive subject)",
"tsalsungay /adv./", "Nevertheless, even so",
"tsam /n./", "War",
"tsam n.", "war ",
"tsampongu /n./", "War party",
"tsampongu n.", "war party",
"tsamsiyu /n./", "Warrior",
"tsamsiyu n.", "warrior ",
"tsap'alute /n./", "Apology",
"tsap'alute n.", "apology ",
"tsap'alute si /vin./", "Apologise (apologize)",
"tsaria /pn., sbd./", "That",
"tsat /pn./", "That, it (as object)",
"tsat pn", "that that (as object)",
"tsata /pn., sbd./", "That",
"tsatseng adv.", "there there, that place",
"tsatseng or [ˈt͡sa.t͡sɛŋ] /dem./", "There, that place",
"tsatseng", "''there''",
"tsatu /dem./", "That person",
"tsatu pn", "that that person",
"tsatu", "''that person''",
"tsaw /dem., pn./", "That, it (as intransitive subject)",
"tsawa /pn., sbd./", "That",
"tsawke /n./", "Sun",
"tsawke n.", "sun ",
"tsawl /adj./", "Big (in size), tall",
"tsawl adj.", "big (in stature)",
"tsawl slu /vin./", "Grow",
"tsawlapxangrr /n./", "Unidelta tree, lit. tall large root",
"tsawlhì' /n./", "Size",
"tse /part./", "Well (conversation starter)",
"tse'a /vtr./", "See (physical sense)",
"tse'a v.", "see (physical sense)",
"tseng /n./", "Place",
"tseng(e) n.", "place ",
"tsenge /n./", "Place",
"tsengo /pn./", "Somewhere",
"tsengpe /inter./", "Where",
"tsengpe adv., conj", "where ",
"tseo /n./", "Art",
"tseo n.", "art ",
"tsewtx /adj./", "Dirty",
"tsim /n./", "Source",
"tskalep /n./", "Crossbow",
"tsko /n./", "Bow (weapon)",
"tsko n.", "bow (weapon)",
"tsko swizaw /n./", "Bow and arrow",
"tsko swizaw n.", "bow and arrow",
"tskxe /n./", "Rock, stone",
"tskxe n.", "rock, stone",
"tskxekeng /n./", "Training, exercise",
"tskxekeng n.", "training, exercise ",
"tskxekeng si /v./", "Exercise, train",
"tslam /vtr./", "Understand",
"tslam v.", "understand ",
"tsleng /adj./", "False",
"tsleng adj.", "false ",
"tslolam (expression)", "Got it. I understand.",
"tslolam /intj./", "Get it, I understand",
"tsmuk /n./", "Sibling",
"tsmuk, tsmuktu n.", "sibling ",
"tsmukan /n./", "Brother",
"tsmukan n.", "brother",
"tsmuke /n./", "Sister",
"tsmuke n.", "sister",
"tsmuktu /n./", "Sibling",
"tsngal /n./", "Cup",
"tsngan /n./", "Meat",
"tsngawvìk /vin./", "Cry, weep",
"tsnì /sbd./", "That (function word)",
"tsnì pn", "that ",
"tsopì /n./", "Lung",
"tspang /vtr./", "Kill",
"tspang v.", "kill",
"tsranten /vin./", "Matter, be of import",
"tsranten v.", "matter be of importance",
"tsray /n./", "Village",
"tsre'i /vtr./", "Throw",
"tstal /n./", "Knife",
"tsteu adj.", "brave",
"tstew /adj./", "Brave",
"tstu /adj./", "Closed, shut",
"tstu si /vin./", "Close",
"tstunwi /adj./", "Kind, thoughtful, considerate",
"tstxa'a /n./", "Canalyd",
"tstxo /n./", "Name",
"tstxolì'u /n./", "Noun",
"tsuksìm /n./", "Chin",
"tsulfä /n./", "Mastery",
"tsulfä si /vin./", "Master",
"tsulfätu /n./", "Master of an art, craft, or skill, expert",
"tsun /vin./", "Can, be able (with subjunctive)",
"tsun v.", "can, be able",
"tsunslu /vin./", "May, be possible",
"tsurokx /v./", "Rest",
"tswa' /v./", "Forget",
"tswayon /vin./", "Fly",
"tswayon v.", "fly",
"tswin /n./", "Queue, braid",
"tswintsyìp /n./", "Little queue",
"tsyal /n./", "Wing",
"tsyal n.", "wing ",
"tsyo /n./", "Flour",
"tsyokx /n./", "Hand",
"tsyorina'wll /n./", "Cycad, flour seed plant",
"tsyosyu /n./", "Food made from flour",
"tsyänel /n./", "TV channel",
"tsyìräfì /n./", "Giraffe",
"tsä' /v./", "Squirt",
"tsìng /num./", "Four",
"tsìng n. , adj.", "four ",
"tsìve /adj./", "Fourth (ordinal)",
"tsìvol n. , adj.", "thirty-two thirty-two (octal: 40)",
"tukru /n./", "Spear",
"tukru n.", "spear",
"tul /vin./", "Run",
"tul v.", "run",
"tumpin /n./", "Red, orange",
"tun /adj./", "Red, orange",
"tung /v./", "Allow",
"tung v.", "allow ",
"tungzup /vtr./", "Drop (ii)",
"tup /conj./", "Instead of, rather than",
"tupe /inter./", "Who",
"tupe adv.", "who",
"tut /part./", "Continuation marker",
"tutan /n./", "Male (person)",
"tute /n./", "Person",
"tute n.", "person",
"tutean n.", "male (person)",
"tutee n.", "female (person)",
"tuteo /pn./", "Somebody, someone",
"tuté /n./", "Female (person)",
"tuvon /v./", "Lean",
"txa' /adj./", "Hard",
"txal /n./", "Back (of the body)",
"txampay /n./", "Sea, ocean",
"txampxì /n./", "Majority, most, large part",
"txan /adj./", "Great, much, many (in quantity)",
"txan adj.", "great, much, many great (in quantity); much",
"txanew /adj./", "Greedy",
"txantsan /adj./", "Excellent",
"txantslusam /adj./", "Wise",
"txantslusam adj.", "wise wise, much-knowing",
"txantstew /n./", "Hero",
"txantur /adj./", "Powerful",
"txayo /n./", "Field, open terrain, plain",
"txe'lan /n./", "Heart",
"txe'lan n.", "heart",
"txei /n./", "Plain",
"txele /n./", "Matter (subject)",
"txele v.", "matter (subject)",
"txen /adj./", "Awake",
"txen adj.", "awake ",
"txep /n./", "Fire",
"txep n.", "fire",
"txeptsyìp /n./", "Dear or cute little fire",
"txepvi /n./", "Spark",
"txewk /n./", "Club (weapon)",
"txey /v./", "Halt",
"txey v.", "halt",
"txin /adj./", "Main, primary",
"txintìn /n./", "Occupation, primary role in society",
"txll'u /n./", "Hookagourd",
"txo /conj./", "If",
"txo conj.", "if",
"txoa /n./", "Forgiveness",
"txoa n.", "forgiveness ",
"txokefyaw /conj./", "If not, or else, otherwise",
"txokefyaw conj.", "if not if not, or else",
"txon /n./", "Night",
"txon n.", "night ",
"txon'ong /n./", "Nightfall, sunset, dusk, gloaming",
"txon'ongmaw /n./", "Twilight, the time before dark, after",
"txonam /adv./", "Last night",
"txonay /adv./", "Tomorrow night",
"txopu /n./", "Fear",
"txopu n.", "fear ",
"txopu si /vin./", "Be afraid",
"txukx /adj./", "Deep (physically)",
"txula /v./", "Build, construct",
"txum /n./", "Poison",
"txum n.", "poison",
"txumpaywll /n./", "Scorpion thistle, poison water plant",
"txumtsä'wll /n./", "Baja tickler, poisonsquirting plant",
"txur /adj./", "Strong (physically)",
"txur adj.", "strong ",
"txärem /n./", "Bone",
"txìm /n./", "Butt, rear end, ass",
"txìm n.", "butt, rear end",
"txìng /v./", "Leave, abandon",
"txìng v.", "leave, abandon ",
"täftxu /vtr./", "Weave",
"täftxu v.", "weave ",
"täftxuyu /n./", "Weaver",
"täftxuyu n.", "weaver",
"tätxaw /vin./", "Return",
"tì'awm /n./", "Camping",
"tì'awm si /vin./", "Camp",
"tì'awpo /n./", "Individuality (negative connotation), selfishness",
"tì'efu /n./", "Feeling",
"tì'em /n./", "The art of cooking",
"tì'eylan /n./", "Friendship",
"tì'eyng /n./", "Answer, response",
"tì'i'avay /adv./", "Until the end",
"tì'o' /n./", "Fun, excitement",
"tì'ong /n./", "Blooming, unfolding",
"tìfmetok /n./", "Test",
"tìfmetok n.", "test",
"tìfnu /n./", "Quiet, silence",
"tìftang /n./", "Stopping, the glottal stop",
"tìftang n.", "stopping ",
"tìftia /n./", "Study",
"tìftia kifkeyä /n./", "Science, the study of the",
"tìftxavang /n./", "Passion",
"tìftxey /n./", "Choice",
"tìfyawìntxu /n./", "Guidance",
"tìfyeyn /n./", "Ripeness, maturity, full fruition",
"tìhawl /n./", "Preparations, plan",
"tìhawnu /n./", "Protection",
"tìhawnu n.", "protection ",
"tìhawnu si /vin./", "Protect",
"tìhawnuwll /n./", "Spartan, protection plant",
"tìk'ìn /n./", "Free time, the absence of business",
"tìkan /n./", "Aim, goal, purpose, target",
"tìkangkem /n./", "Work",
"tìkangkem si /vin./", "Work",
"tìkangkemvi /n./", "Project, piece of work",
"tìkanu /n./", "Intelligence",
"tìkawng /n./", "Evil",
"tìkawng adj.", "evil ",
"tìkenong /n./", "Example",
"tìkenong n.", "example ",
"tìketeng /n./", "Difference",
"tìkin /n./", "Need",
"tìkin v.", "need ",
"tìkusar /n./", "Teaching (the act)",
"tìkxey /n./", "Incorrectness, mistakeness",
"tìkxey si /vin./", "Mess up, foul, do wrong",
"tìlam /n./", "Appearance",
"tìlen /n./", "Event, happening",
"tìlor /n./", "Beauty",
"tìm /adj./", "Low",
"tìme'em /n./", "Harmony (general sense)",
"tìmok /n./", "Suggestion",
"tìmuntxa /n./", "Mating, marriage",
"tìmweypey /n./", "Patience",
"tìn /n./", "Activity that keeps one busy",
"tìng /v./", "Give",
"tìng mikyun /vin./", "Listen",
"tìng mikyun v.", "listen ",
"tìng nari /vin./", "Look",
"tìng nari v.", "look ",
"tìng tseng /vin./", "Back down, give ground",
"tìng v.", "give",
"tìngay /n./", "Truth",
"tìngay n.", "truth ",
"tìngop /n./", "Creation",
"tìngäzìk /n./", "Difficulty, problem",
"tìno /n./", "Thoroughness, attention to detail",
"tìnomum /n./", "Curiosity",
"tìoeyktìng /n./", "Explanation",
"tìohakx /n./", "Hunger",
"tìpawm /n./", "Question",
"tìpe'un /n./", "Decision",
"tìprrte' /n./", "Pleasure",
"tìpähem /n./", "Arrival",
"tìpängkxo /n./", "Conversation, discussion",
"tìpängkxotsyìp /n./", "Little conversation",
"tìran /vin./", "Walk",
"tìran v.", "walk ",
"tìrey /n./", "Life",
"tìrey n.", "life ",
"tìrol /n./", "Song (vocal)",
"tìrol n.", "song ",
"tìska'a /n./", "Destruction",
"tìsom /n./", "Heat",
"tìsop /n./", "Journey",
"tìspe'e /n./", "Capture",
"tìspxin /n./", "The state of being ill, sickness",
"tìsraw /n./", "Pain",
"tìsraw seyki /vtr./", "Hurt (someone or something)",
"tìsraw si /vin./", "Hurt, be painful",
"tìsrese'a /n./", "Prophecy",
"tìsti /n./", "Anger",
"tìsung /n./", "Addition, post script (P.S.)",
"tìtakuk /n./", "Strike",
"tìtslam /n./", "Understanding, intelligence",
"tìtstunwi /n./", "Kindness",
"tìtusaron /n./", "Hunting",
"tìtxanew /n./", "Greed",
"tìtxen /n./", "Awakeness, the state of waking",
"tìtxula /n./", "Construction, constructed thing",
"tìtxur /n./", "Strength, power",
"tìtxur n.", "strength",
"tìvawm /n./", "Darkness",
"tìve'kì /n./", "Hatred",
"tìwew /n./", "Coldness, cold",
"tìwusem /n./", "Fighting",
"tìyawn /n./", "Love",
"tìyawr /n./", "Correctness",
"tìyusom /n./", "Eating (the act)",
"u'imi /n./", "Streamer, pendant",
"uk /n./", "Shadow",
"ukxo /adj./", "Dry",
"ulte /conj./", "And (clausal conjunction)",
"ulte conj.", "and",
"ultxa /n./", "Meeting",
"ultxa n.", "meeting",
"ultxa si /vin./", "Meet with someone intentionally (use with)",
"ultxarun /v./", "Encounter, meet by chance (ii)",
"unil /n./", "Dream",
"unil n.", "dream ",
"uniltìrantokx /n./", "Avatar, dreamwalker body",
"uniltìrantokx n.", "avatar, dreamwalker body ",
"uniltìranyu /n./", "Dreamwalker",
"uniltìranyu n.", "dreamwalker",
"uo /adp./", "Behind",
"utral /n./", "Tree",
"utral n.", "tree ",
"utral utu mauti /n./", "Push fruit tree",
"utraltsyìp /n./", "Bush",
"utu mauti /n./", "Banana fruit, push fruit",
"uvan /n./", "Game, uvan letokx sport",
"uvan si /vin./", "Play (a game)",
"vawm /adj./", "Dark",
"vawmpin /n./", "Dark color",
"vay /adp./", "Up to",
"vaykrr /conj./", "Until",
"ve'kì /vtr./", "Hate",
"venu /n./", "Foot",
"venzek /n./", "Toe",
"vewng /vtr./", "Look after, take care of, be responsible for",
"vey /n./", "Food made from animal origin, flesh",
"virä /v./", "Spread, proliferate",
"virä v.", "spread, proliferate ",
"vitra /n./", "Soul",
"vofu n. , adj.", "sixteen ",
"vol /num./", "Eight",
"volve /adj./", "Eighth (ordinal)",
"vrrtep /n./", "Demon",
"vrrtep n.", "demon ",
"vrrìn /vin./", "Be busy (negative sense): be tired out and",
"vul /n./", "Branch (of a tree)",
"vul n.", "branch (of a tree)",
"vur /n./", "Story",
"vurvi /n./", "Summary, synopsis",
"vä' /adj./", "Unpleasant to the senses, noisome",
"väfewll /n./", "Centipede, badsmell plant",
"värumut /n./", "Vein pod",
"way /n./", "Song (ancient, ceremonial)",
"way n.", "song ",
"way si /vin./", "Sing",
"waytelem /n./", "Song chord",
"waytelem n.", "songchord ",
"wem /vin./", "Fight",
"wempongu /n./", "Squad, military clan, battle party",
"wew /adj./", "Cold",
"weyn /v./", "Draw, illustrate",
"win /adj./", "Fast",
"win si /vin./", "Rush something, make something fast",
"win säpi /vin./", "Hurry",
"wintxu v.", "show",
"wiya /intj./", "Expression of warning or frustration, 'damn!'",
"wok /adj./", "Loud",
"wotx /n./", "Totality, whole",
"wou /svin./", "Be amazing, fascinating (slang)",
"wrrpa /n., adv./", "Outside",
"wrrpa adj.", "outside",
"wutso /n./", "Dinner, served meal",
"wutso n.", "dinner dinner, served meal",
"wä /adp./", "Against (as in: fight against)",
"wätx /vtr./", "Be bad at",
"wìntxu /v./", "Show",
"ya /n./", "Air",
"yapay /n./", "Mist, fog, steam",
"yawne /adj./", "Beloved",
"yawnetu /n./", "Loved one",
"yawntu /n./", "Loved one",
"yaymak /adj./", "Foolish, ignorant",
"yayo /n./", "Bird",
"ye'krr /adv./", "Early",
"ye'rìn /adv./", "Soon",
"ye'rìn adv.", "soon",
"yem /vtr./", "Put, place",
"yemfpay /n./", "Dipping, immersion (into liquid)",
"yemfpay si /vin./", "Dip into liquid",
"yerik /n./", "Hexapede",
"yey /adj./", "Straight",
"yey adj.", "straight ",
"yol /adj./", "Short (of time)",
"yol adj.", "long (period of time)",
"yom /vtr./", "Eat",
"yom v.", "eat ",
"yomhì'ang /n./", "Small animal/insect eater, dakteron",
"yomioang /n./", "Chalice plant",
"yomtìng /vin./", "Feed (with dative object) (ii)",
"yomtìng v.", "feed ",
"yur /v./", "Wash",
"yur v.", "wash ",
"yän /vtr./", "Fasten, tie down",
"yìm /vtr./", "Bind",
"yìm v.", "bind ",
"za'u /vin./", "Come",
"za'u nì'eng /phrase/", "Share an interest in common",
"za'u v.", "come ",
"za'ärìp /vtr./", "Pull",
"za'ärìp v.", "pull ",
"zam /num./", "Sixty four",
"zamunge /vtr./", "Bring",
"zamunge v.", "bring ",
"zapxì /n./", "Front (part or section)",
"zawng /vin./", "Scream",
"zekwä /n./", "Finger",
"zekwä n.", "finger ",
"zene /vin./", "Must (with subjunctive)",
"zene v.", "must ",
"zenke /vin./", "Must not (with subjunctive) (ii)",
"zerok /v./", "Remember",
"zeyko /vtr./", "Heal, fix",
"zize' /n./", "Hellfire wasp",
"zo /vin./", "Be well, be intact, be as it should be, work correctly",
"zong /v./", "Save, defend",
"zong v.", "save ",
"zongtseng /n./", "Safe place, refuge",
"zongtseng n.", "safe place, refuge ",
"zoplo /n./", "Offence, insult",
"zoplo n.", "offence, insult ",
"zoslu /vin./", "Heal, become well, get fixed",
"zup /vin./", "Fall",
"zusawkrr /n./", "Future",
"zìsìkrr /n./", "Season",
"zìsìt /n./", "Year",
"zìsìt n.", "year ",
"Änsìt n.", "child's name",
"äie /n./", "Vision (spiritual)",
"äie n.", "vision ",
"äo /adp./", "Below",
"ätxäle /n./", "Request",
"ätxäle n.", "request ",
"ätxäle si /vin./", "Request (with tsnì clause for object)",
"ìley /intj./", "War cry",
"ìlä (also: ìlä) adv.", "by, via, following ",
"ìlä or [ɪ.ˈlæ] /adp./", "By, via, following",
"ìpxa /n./", "Fern"
 };

    // send out message that we loaded the language
    public static void wrdcnt(){
	int wcount = language.length/2;
	System.out.println ("Language contains " + wcount + " words.");
    }
public	uDNVlang (){
	    // overwrite language array with new language
	    String [] tmpVar = new String[edict.length];
	    System.arraycopy(edict,0,tmpVar,0,edict.length);
	    language = tmpVar;
	}
    public String tranString(String inText) {
	// Not valid in UDPhrases
	// parse each word with English meaning
	return "\n\nUse this to look up phrases and words.\nParsing not available.";


    }	
}
